require: rubocop-rails
AllCops:
  TargetRubyVersion: 2.6.0
  Exclude:
    - 'db/schema.rb'
    - 'tmp'
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/support/*'
    - 'spec/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Style/RedundantReturn:
  Enabled: false

Style/SignalException:
  Enabled: true
  EnforcedStyle: 'semantic'

####################################################################
# From https://github.com/bbatsov/rubocop/blob/master/.rubocop.yml #
####################################################################
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
